In [1]:
import kagglehub
path = kagglehub.dataset_download("iamsouravbanerjee/customer-shopping-trends-dataset")

Downloading to /root/.cache/kagglehub/datasets/iamsouravbanerjee/customer-shopping-trends-dataset/2.archive...

100%|██████████| 146k/146k [00:00<00:00, 381kB/s]

Extracting files...

In [2]:
import os
import pandas as pd

# List contents of the downloaded path to find the dataset file(s)
print(f"Contents of the downloaded path: {os.listdir(path)}")

Contents of the downloaded path: ['shopping_trends_updated.csv', 'shopping_trends.csv']

Please examine the output from the previous cell and tell me the exact filename of the CSV file. For example, if the output shows `['customer_shopping_trends.csv']`, then the filename is `customer_shopping_trends.csv`.

In [3]:
file_name = 'shopping_trends_updated.csv'
df = pd.read_csv(os.path.join(path, file_name))
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import numpy as np

# Define target and features
X = df.drop(['Customer ID', 'Purchase Amount (USD)'], axis=1)
y = df['Purchase Amount (USD)']

# Identify categorical and numerical features
categorical_features = X.select_dtypes(include=['object']).columns
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Create a pipeline with preprocessing and a placeholder for the model
# We'll add the model later after the data is transformed and split
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Apply preprocessing to the features
X_processed = pipeline.fit_transform(X)

# Get feature names after one-hot encoding for categorical features
# This helps in understanding the columns of the processed data
cat_feature_names = pipeline.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(categorical_features)
all_feature_names = list(numerical_features) + list(cat_feature_names)

print(f"Original features: {X.columns.tolist()}")
print(f"Numerical features: {numerical_features.tolist()}")
print(f"Categorical features: {categorical_features.tolist()}")
print(f"Shape of preprocessed features: {X_processed.shape}")

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

Original features: ['Age', 'Gender', 'Item Purchased', 'Category', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']
Numerical features: ['Age', 'Review Rating', 'Previous Purchases']
Categorical features: ['Gender', 'Item Purchased', 'Category', 'Location', 'Size', 'Color', 'Season', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Payment Method', 'Frequency of Purchases']
Shape of preprocessed features: (3900, 142)
X_train shape: (3120, 142), y_train shape: (3120,)
X_test shape: (780, 142), y_test shape: (780,)

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the deep learning model
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])

# Display model summary
model.summary()

# Train the model
history = model.fit(
    X_train,
    y_train,
    epochs=50, # You can adjust the number of epochs
    batch_size=32,
    validation_split=0.2, # Use a portion of training data for validation
    verbose=1
)

# Evaluate the model on the test set
loss, mae = model.evaluate(X_test, y_test, verbose=0)
print(f"\nModel Evaluation on Test Set:")
print(f"Mean Squared Error: {loss:.4f}")
print(f"Mean Absolute Error: {mae:.4f}")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │        18,304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 28,673 (112.00 KB)

 Trainable params: 28,673 (112.00 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 2185.4939 - mean_absolute_error: 38.8601 - val_loss: 558.0839 - val_mean_absolute_error: 20.4211
Epoch 2/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 565.6393 - mean_absolute_error: 20.5595 - val_loss: 547.0080 - val_mean_absolute_error: 20.3189
Epoch 3/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 551.4605 - mean_absolute_error: 20.2501 - val_loss: 550.5673 - val_mean_absolute_error: 20.3400
Epoch 4/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 549.5687 - mean_absolute_error: 20.1620 - val_loss: 565.3888 - val_mean_absolute_error: 20.4977
Epoch 5/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 542.5425 - mean_absolute_error: 19.9832 - val_loss: 558.9481 - val_mean_absolute_error: 20.4228
Epoch 6/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 534.6943 - mean_absolute_error: 19.8634 - val_loss: 559.3962 - val_mean_absolute_error: 20.3864
Epoch 7/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 528.3336 - mean_absolute_error: 19.7208 - val_loss: 562.7039 - val_mean_absolute_error: 20.3914
Epoch 8/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 519.7009 - mean_absolute_error: 19.4986 - val_loss: 587.2649 - val_mean_absolute_error: 20.7501
Epoch 9/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 507.5010 - mean_absolute_error: 19.2627 - val_loss: 567.0472 - val_mean_absolute_error: 20.3954
Epoch 10/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 492.5348 - mean_absolute_error: 18.9394 - val_loss: 574.3433 - val_mean_absolute_error: 20.4985
Epoch 11/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 470.7284 - mean_absolute_error: 18.4924 - val_loss: 579.7791 - val_mean_absolute_error: 20.5348
Epoch 12/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 451.3545 - mean_absolute_error: 18.0405 - val_loss: 585.8303 - val_mean_absolute_error: 20.5258
Epoch 13/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 423.7597 - mean_absolute_error: 17.4312 - val_loss: 603.5753 - val_mean_absolute_error: 20.7816
Epoch 14/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 394.5544 - mean_absolute_error: 16.7136 - val_loss: 627.3673 - val_mean_absolute_error: 20.9497
Epoch 15/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 362.5498 - mean_absolute_error: 16.0205 - val_loss: 624.3934 - val_mean_absolute_error: 20.9140
Epoch 16/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 334.0135 - mean_absolute_error: 15.2300 - val_loss: 657.3113 - val_mean_absolute_error: 21.4122
Epoch 17/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 301.8587 - mean_absolute_error: 14.3993 - val_loss: 679.2672 - val_mean_absolute_error: 21.6806
Epoch 18/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 274.4642 - mean_absolute_error: 13.6909 - val_loss: 718.6004 - val_mean_absolute_error: 22.1506
Epoch 19/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 259.6614 - mean_absolute_error: 13.2523 - val_loss: 719.1714 - val_mean_absolute_error: 22.0370
Epoch 20/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 230.4184 - mean_absolute_error: 12.4378 - val_loss: 780.7400 - val_mean_absolute_error: 22.9282
Epoch 21/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 208.0994 - mean_absolute_error: 11.6716 - val_loss: 778.0771 - val_mean_absolute_error: 22.8096
Epoch 22/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 193.4023 - mean_absolute_error: 11.1938 - val_loss: 792.0388 - val_mean_absolute_error: 22.9567
Epoch 23/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.2248 - mean_absolute_error: 10.7228 - val_loss: 819.7464 - val_mean_absolute_error: 23.3270
Epoch 24/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 157.5124 - mean_absolute_error: 10.1353 - val_loss: 858.9415 - val_mean_absolute_error: 23.7031
Epoch 25/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 148.2863 - mean_absolute_error: 9.7698 - val_loss: 862.3397 - val_mean_absolute_error: 23.7559
Epoch 26/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 130.9011 - mean_absolute_error: 9.1837 - val_loss: 887.2506 - val_mean_absolute_error: 24.0082
Epoch 27/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 122.5432 - mean_absolute_error: 8.8821 - val_loss: 927.2145 - val_mean_absolute_error: 24.3447
Epoch 28/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 111.0241 - mean_absolute_error: 8.4264 - val_loss: 935.5294 - val_mean_absolute_error: 24.5197
Epoch 29/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 95.3611 - mean_absolute_error: 7.7149 - val_loss: 928.7592 - val_mean_absolute_error: 24.4520
Epoch 30/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 85.7630 - mean_absolute_error: 7.3586 - val_loss: 967.0513 - val_mean_absolute_error: 24.9627
Epoch 31/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 79.6298 - mean_absolute_error: 7.0547 - val_loss: 947.3142 - val_mean_absolute_error: 24.5895
Epoch 32/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 70.2512 - mean_absolute_error: 6.6575 - val_loss: 975.0165 - val_mean_absolute_error: 24.8996
Epoch 33/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 60.6249 - mean_absolute_error: 6.1516 - val_loss: 997.4088 - val_mean_absolute_error: 25.1667
Epoch 34/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 52.3810 - mean_absolute_error: 5.6885 - val_loss: 1003.1211 - val_mean_absolute_error: 25.1821
Epoch 35/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 48.2064 - mean_absolute_error: 5.5022 - val_loss: 1037.4708 - val_mean_absolute_error: 25.6897
Epoch 36/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42.9050 - mean_absolute_error: 5.1846 - val_loss: 1034.4296 - val_mean_absolute_error: 25.5058
Epoch 37/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.9066 - mean_absolute_error: 4.7062 - val_loss: 1028.8580 - val_mean_absolute_error: 25.3998
Epoch 38/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31.1499 - mean_absolute_error: 4.3623 - val_loss: 1029.6967 - val_mean_absolute_error: 25.3495
Epoch 39/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.9923 - mean_absolute_error: 4.2272 - val_loss: 1049.1945 - val_mean_absolute_error: 25.6636
Epoch 40/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.5030 - mean_absolute_error: 3.7867 - val_loss: 1036.3214 - val_mean_absolute_error: 25.5818
Epoch 41/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.6600 - mean_absolute_error: 3.6001 - val_loss: 1052.7231 - val_mean_absolute_error: 25.7060
Epoch 42/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 17.1993 - mean_absolute_error: 3.2238 - val_loss: 1060.3856 - val_mean_absolute_error: 25.8542
Epoch 43/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.6403 - mean_absolute_error: 3.1202 - val_loss: 1078.7938 - val_mean_absolute_error: 26.0169
Epoch 44/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.0601 - mean_absolute_error: 2.8737 - val_loss: 1065.2441 - val_mean_absolute_error: 25.8128
Epoch 45/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 12.0208 - mean_absolute_error: 2.7385 - val_loss: 1079.4071 - val_mean_absolute_error: 25.9707
Epoch 46/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3490 - mean_absolute_error: 2.5617 - val_loss: 1074.4452 - val_mean_absolute_error: 25.9343
Epoch 47/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.8312 - mean_absolute_error: 2.3460 - val_loss: 1086.7361 - val_mean_absolute_error: 26.0674
Epoch 48/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.3256 - mean_absolute_error: 2.1414 - val_loss: 1081.1849 - val_mean_absolute_error: 26.0176
Epoch 49/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.6944 - mean_absolute_error: 2.0509 - val_loss: 1086.1843 - val_mean_absolute_error: 25.9113
Epoch 50/50
78/78 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0415 - mean_absolute_error: 1.9545 - val_loss: 1078.4703 - val_mean_absolute_error: 25.9506

Model Evaluation on Test Set:
Mean Squared Error: 1031.1233
Mean Absolute Error: 25.9869

In [7]:
# Install Streamlit
!pip install streamlit joblib -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 31.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 54.0 MB/s eta 0:00:00

In [8]:
import joblib
import tensorflow as tf

# Save the preprocessor pipeline
joblib.dump(pipeline, 'preprocessor.joblib')

# Save the Keras model
model.save('deep_learning_model.keras')

print("Preprocessor and model saved successfully.")

Preprocessor and model saved successfully.

In [21]:
%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
import os

# Define the path to the dataset - this needs to be accessible from within the app
DATASET_PATH = '/root/.cache/kagglehub/datasets/iamsouravbanerjee/customer-shopping-trends-dataset/versions/2/shopping_trends_updated.csv'

# Load the preprocessor and model
preprocessor_pipeline = joblib.load('preprocessor.joblib')
deep_learning_model = tf.keras.models.load_model('deep_learning_model.keras')

# Load the original dataframe to get feature names and unique categorical values
df_original = pd.read_csv(DATASET_PATH)

# Define X and original_features from the reloaded dataframe
X_original = df_original.drop(['Customer ID', 'Purchase Amount (USD)'], axis=1)
original_features = X_original.columns.tolist()

# --- Main App Content ---
st.title('🛒 Customer Purchase Amount Predictor 💰')
st.write('Welcome! Use the sidebar to enter customer details and predict their shopping spend.')

# --- Sidebar for Input ---
st.sidebar.title('📝 Enter Customer Details')
st.sidebar.write('Adjust the parameters below to get a purchase amount prediction.')

input_data = {}

# Numerical features in sidebar
numerical_features = ['Age', 'Review Rating', 'Previous Purchases']
for feature in numerical_features:
    if feature == 'Review Rating':
        input_data[feature] = st.sidebar.slider(f'Select {feature}', 1.0, 5.0, 3.5, 0.1)
    elif feature == 'Age':
        input_data[feature] = st.sidebar.slider(f'Select {feature}', 18, 70, 30)
    else: # Previous Purchases
        input_data[feature] = st.sidebar.number_input(f'Enter {feature}', min_value=0, value=10)

# Categorical features in sidebar
categorical_features = [f for f in original_features if f not in numerical_features]

for feature in categorical_features:
    unique_vals = df_original[feature].unique().tolist()
    input_data[feature] = st.sidebar.selectbox(f'Select {feature}', unique_vals)

# Predict button in the main area for better visibility
if st.button('🚀 Predict Purchase Amount'):
    # Create a DataFrame from input data
    input_df = pd.DataFrame([input_data])

    # Create a dummy DataFrame with all original features and then fill it with user input
    # This is crucial for `ColumnTransformer` to work correctly and maintain feature order
    dummy_df = pd.DataFrame(columns=original_features)
    dummy_df = pd.concat([dummy_df, input_df], ignore_index=True)

    # Ensure input_df has all original_features, in the correct order
    processed_input = preprocessor_pipeline.named_steps['preprocessor'].transform(dummy_df[original_features])

    # Make prediction
    prediction = deep_learning_model.predict(processed_input)[0][0]

    st.success(f'### Predicted Purchase Amount (USD): ${prediction:.2f} 💸')

st.markdown("---")
st.markdown("💡 *This model predicts potential customer spending based on various shopping trends attributes.*")

Overwriting app.py

To run the Streamlit app, execute the next cell. After running, a link will appear, usually resembling `your_ip_address:8501`. Click on this link to open the app in a new tab.

In [12]:
!pip install --ignore-installed blinker
!pip install streamlit

Collecting blinker
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Installing collected packages: blinker
Successfully installed blinker-1.9.0

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.62.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.3)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)

In [13]:
!pip install streamlit pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.62.0)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.3)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.2)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.24.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [14]:
from pyngrok import ngrok
ngrok.set_auth_token("3H2nxZtP4iC5L9tX9K97OPLut9W_4JsZrRVF5aRFQpQCCePy1")

In [22]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://vanity-amperage-commodore.ngrok-free.dev" -> "http://localhost:8501"

In [23]:
# Run the Streamlit app
# This will provide a public URL to access the app
!streamlit run app.py &

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

WARNING:pyngrok.process.ngrok:t=2026-08-20T12:51:19+0000 lvl=warn msg="failed to open private leg" id=3e7ed6972180 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-20T12:51:19+0000 lvl=warn msg="failed to open private leg" id=6eb1d6066be8 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-20T12:51:19+0000 lvl=warn msg="failed to open private leg" id=0b64e744b0f1 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

2026-08-20 12:51:19.730 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.185.137.107:8501

2026-08-20 12:51:30.611301: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/content/app.py:57: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dummy_df = pd.concat([dummy_df, input_df], ignore_index=True)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
  Stopping...

In [10]:
!streamlit run app.py --server.port 8501

Usage: streamlit run [OPTIONS] [TARGET] [ARGS]...
Try 'streamlit run --help' for help.

Error: Invalid value: File does not exist: app.py